---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.7.0
    replicas: 1
    listeners:
      - name: kafka
        port: 9093
        type: route # use an OpenShift route
        tls: true
        authentication:
          type: tls
      - name: plain
        port: 29092
        type: internal
        tls: false
      - name: tls
        port: 29093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: scram
        port: 29094
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
    authorization:
      type: simple
      superUsers:
        - kafkaadmin
        - CN=kafkaadmintls
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.7"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafkaadmin
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
#  authorization:
#    type: simple
#    acls: []
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafkaadmintls
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
